# Build Stage
FROM node:18-alpine AS BUILD_IMAGE

WORKDIR /app

COPY package*.json ./
RUN npm install -g pnpm && pnpm install

COPY . .
RUN pnpm build

# Production Stage
FROM node:18-alpine AS PRODUCTION_STAGE

WORKDIR /app

RUN npm install -g pnpm

COPY --from=BUILD_IMAGE /app/package*.json ./
COPY --from=BUILD_IMAGE /app/.next ./.next
COPY --from=BUILD_IMAGE /app/public ./public
COPY --from=BUILD_IMAGE /app/node_modules ./node_modules

ENV NODE_ENV=production
